### ISSUE TITLE
Entities in (policy.)mcm.ibm.com group are rejected

### ISSUE THREAD

**Issue by ahadas** [open-cluster-management/multicloud-operators-subscription#166]
The following scenario that used to work with previous versions of OCM:
1. Have a local appsub with a github channel
2. Store policies and placementbindings in the repo
3. The policies and placementbindings would be added to the hub cluster.

Doesn't work with the latest version, it fails with [this error](https://github.com/open-cluster-management/multicloud-operators-subscription/blob/7c7d2c9961ff64e89a08803af26cab61532eb6a3/pkg/subscriber/github/subscriber_item.go#L433)

@mdelder @jnpacker  fyi

**Comment by ahadas** [comment]
It doesn't fail on policies and placementbindings anymore but we get the same error on other non-Kubernetes resources:
```
I0421 17:06:26.795155       1 gitrepo.go:369] kubevirt.io/v1alpha3/KubeVirt
W0421 17:06:26.795269       1 gitrepo.go:76] Not a Kubernetes resource
I0421 17:06:26.797963       1 gitrepo.go:386] Multi resource
I0421 17:06:26.798020       1 gitrepo.go:340] otherFiles size ^B
W0421 17:06:26.798052       1 helmrepo.go:373] subsciption.spec.name is missing for subscription: ec/cnv-appsub
W0421 17:06:26.798197       1 gitrepo.go:76] Not a Kubernetes resource
I0421 17:06:26.798479       1 subscriber_item.go:284] Skipping resource
E0421 17:06:26.798635       1 subscriber_item.go:270] Failed to apply a resource, error: Resource kubevirt.io/v1alpha3, Kind=KubeVirt is
 not supported
```

**Comment by ianzhang366** [comment]
When I was trying this  with `apiextensions.k8s.io/v1` on my own, I hit the following part,  #166

```
I0421 17:06:26.795155       1 gitrepo.go:369] kubevirt.io/v1alpha3/KubeVirt
W0421 17:06:26.795269       1 gitrepo.go:76] Not a Kubernetes resource
I0421 17:06:26.797963       1 gitrepo.go:386] Multi resource
I0421 17:06:26.798020       1 gitrepo.go:340] otherFiles size ^B
W0421 17:06:26.798052       1 helmrepo.go:373] subsciption.spec.name is missing for subscription: ec/cnv-appsub
W0421 17:06:26.798197       1 gitrepo.go:76] Not a Kubernetes resource
I0421 17:06:26.798479       1 subscriber_item.go:284] Skipping resource
E0421 17:06:26.798635       1 subscriber_item.go:270] Failed to apply a resource, error: Resource kubevirt.io/v1alpha3, Kind=KubeVirt is
 not supported
```
FYI, [yaml used to reproduce](https://github.com/ianzhang366/acm-applifecycle-samples/tree/master/crd-deploy)

Checking the logic, it seems that the CR is not requeue correctly. The flow goes this way,
1. CRD and CR is pulled from github and apply to cluster
2. CRD will be applied, and CR will be rejected, since on manged cluster, we don't have a CRD to support CR
3. CRD applied successfully, and CRD cache is updated
4. GitHub `doSubscription()` kicks in, however, since the git commit ID doesn't change, so we won't retry the CR.

https://github.com/open-cluster-management/multicloud-operators-subscription/blob/4c146908ef91cf8fb3f9da866c1c539f9f5334dd/pkg/subscriber/github/subscriber_item.go#L114-L125

@rokej do you think if we can find a way to re-queue the CR? It seems if we have multiple resources within the same git commit, then the failed one won't be retried.

**Comment by ianzhang366** [comment]
@ahadas  I was test a workaround, 

So, we can workaround by the following,
1. update the CRD at `v1` version
2. wait till the CRD deployed then fake a new commit id for your CR, (you can just add some empty space on your CR and commit to github)

In this way, the CRD and CR should be deployed correctly.

**Comment by ahadas** [comment]
@ianzhang366 as for the workaround, would removing the CR to trigger the creation of the CR again by the subscription contoller also do the trick without polluting the repository?

regarding a proper fix, I'd suggest to look at how Argo CD addresses this:
https://github.com/argoproj/argo-cd/pull/1999/

**Comment by ianzhang366** [comment]
@ahadas sry about the late reply.

Thanks for the Argo CD sample, I believe @rokej  is helping us adding similar logic.

> @ianzhang366 as for the workaround, would removing the CR to trigger the creation of the CR again by the subscription contoller also do the trick without polluting the repository?

I don't quite catch your idea. To me, this issue is the CR is not applying to our cluster. then how can you remove the CR?

Another way, I can think of is using 2 separate subscriptions for your CRD and CR, then you can delete and reapply the subscription for CR once the CRD is applied to your cluster. In this way, you don't need to touch your source repo.

@rokej  please feel free to correct me over here.

**Comment by jnpacker** [comment]
@ianzhang366 I have seen this error about the kind not being supported and spoke with @rokej. Sometimes it resolves itself, but here is an example:
```
E0423 21:21:59.077006       1 subscriber_item.go:233] Failed to apply a resource, error: Resource mcm.ibm.com/v1alpha1, Kind=PlacementBinding is not supported
```
There is no CRD in my Github as placementBinding was deployed with ACM.  This is the following subscription, I find sometimes it works and sometimes it doesnt.
https://github.com/open-cluster-management/demo-subscription-gitops/tree/master/policy/subscription

**Comment by rokej** [comment]
Previous subscription controller applied the CRD but failed to apply the CR because at the time of applying the CR, the CRD was not ready. The new controller will apply any failed resources until all of the resources in the subscription are applied successfully. In this particular case, the second attempt of applying the CR should succeed.

**Comment by rokej** [comment]
1.0.0-SNAPSHOT-2020-04-24-01-14-43 or newer should contain this fix.

**Comment by ahadas** [comment]
> I don't quite catch your idea. To me, this issue is the CR is not applying to our cluster. then how can you remove the CR?

Yeah, I had a typo - I meant removing the appsub but then I guess the resources that have already been applied are removed...

**Comment by ahadas** [comment]
> Previous subscription controller applied the CRD but failed to apply the CR because at the time of applying the CR, the CRD was not ready. The new controller will apply any failed resources until all of the resources in the subscription are applied successfully. In this particular case, the second attempt of applying the CR should succeed.

Well, the last part depends on the application - it may be the case that the CRD is defined by an operator and it takes it some time until it gets the CRD registered in addition to the time it takes to k8s to expose this new CRD. So it won't not necessarily work on the second time.

But I can confirm that it works now.

Please see #180  that is also somehow related.

**Comment by rokej** [comment]
I made this comment in https://github.com/open-cluster-management/multicloud-operators-subscription/issues/180 as well.

The subscription applies CRDs and namespaces first. Then it applies RBAC related resource if there is any. You can also use `kustomize` to get a correct ordered list of resources. 

Also with the code fix, the subscription will go back to apply failed resources until they are all applied so even with a wrong order, everything will eventually be applied.

**Comment by jnpacker** [comment]
@rokej can you close this if it has been addressed.

**Comment by rokej** [comment]
@ahadas Can I close this?

**Comment by ahadas** [comment]
@rokej from my side - yes, if you merged a fix and checked that it works now you can close it. if one finds that it's not resolve, it can be reopen.
